# Generated by Django 2.2.13 on 2021-09-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmodel',
            name='unique_model_in_shop',
        ),
    ]
