# Generated by Django 2.2.13 on 2021-09-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210918_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='api.ProductModel', verbose_name='Характеристики'),
        ),
    ]
